version: '3'

services:
        databaseos:
                image: mysql:5.7
                volumes: 
                        - mysql_storage:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: tabish
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydb
        

       
        wpos1:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on: 
                        - databaseos
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_HOST: databaseos
                        WORDPRESS_DB_USER: tabish
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: mydb
                volumes:
                        - wp_storage:/var/www/html

        


        wpos2:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on: 
                        - databaseos
                ports:
                        - 8081:80
                environment:
                        WORDPRESS_DB_HOST: databaseos
                        WORDPRESS_DB_USER: tabish
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: mydb
                volumes:
                        - wp_storage:/var/www/html



volumes:
        wp_storage:
        mysql_storage:
